### ISSUE TITLE
Fejlesztőkörnyezet telepítése

### ISSUE THREAD

**Issue by macakzsolt** [borazslo/szentiras.hu#140]
Próbáltam a [leírtak szerint](https://github.com/borazslo/szentiras.hu/wiki/Fejleszt%C5%91i-tudnival%C3%B3k) összehozni egy fejlesztőkörnyezetet többszöri nekifutással a gépemen de az eredmény az hogy ezt kapom… 

![2017-02-23 10_17_02-mozilla firefox](https://cloud.githubusercontent.com/assets/1118907/23253046/6429604a-f9b3-11e6-9316-3e0b1ab69fd4.png)

Homestead.yaml módosítottam máshoz nem is nagyon kellet nyúlni, ssh működik a virtuális gépre (Virtualbox) be tudok jelentkezni de dev oldal mégsem jön be a fönti hibát kapom.
/bootstrap/../vendor/autoload.php útvonal válóban nem létezik de bárhogy próbáltam módosítani rendre egyere több hibát kapok... 
Van valami ötletetek mi lehet nálam a gond?

Homestead.yaml tartalma:
```
ip: "172.16.15.17"
#ip: "127.0.0.1"
memory: 2048
cpus: 1
provider: virtualbox

authorize: C:/Users/rg/.ssh/id_rsa.pub

keys:
    - C:/Users/rg/.ssh/id_rsa

folders:
    - map: C:\xampp\htdocs
      to: /home/vagrant/Code
sites:
    - map: dev.szentiras.hu
      to: /home/vagrant/Code/szentiras.hu/public
databases:
    - szentiras
```
