### ISSUE TITLE
Olvashatóság

### ISSUE THREAD

**Issue by szepeviktor** [borazslo/szentiras.hu#147]
Népszerűen elterjedt álláspont, hogy asztali monitoron 600px szélesség felett nehéz az olvasás,
mint a tenisz mérkőzésen jobbra-balra kell tekingetni.

Lehetséges lenne 600-ra korlátozni a szélességet?

```css
.parsedVerses {
    max-width: 600px;
}
```
